/**
 * svelte.config.js — Svelte 5 compiler configuration
 *
 * compilerOptions.runes:true  enables Svelte 5 runes ($state, $derived, $effect).
 * preprocess with svelte-preprocess({ script:true }) strips TypeScript from <script lang="ts">
 * blocks so webpack can ingest the output without a full type-check pass (tsc owns that).
 *
 * Generated by Task 1.4. Consumed by svelte-loader via the `config` option.
 */

"use strict";

const sveltePreprocess = require("svelte-preprocess");

module.exports = {
  preprocess: sveltePreprocess({ script: true }),
  compilerOptions: {
    runes: true,
  },
};
